# This is a basic workflow to help you get started with Actions

name: ScheduleTest

on:
  schedule:
  - cron: '*/5 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
