name: Packer Build - 2019

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 20 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: actions/checkout@master

      - name: packer build windows_server_2019.json 
        uses: docker://hashicorp/packer:1.6.4
        with:
          args: build -var "azure_subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" -var "azure_client_id=${{ secrets.ARM_CLIENT_ID }}" -var "azure_tenant_id=${{ secrets.ARM_TENANT_ID  }}" -var "azure_client_secret=${{ secrets.ARM_CLIENT_SECRET }}"  windows_server_2019.json 